spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist_db?useSSL=false&serverTimezone=UTC
    username: root
    password: lnxbd321
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true